### ISSUE TITLE
Update Express plugin documentation

### ISSUE THREAD

**Issue by shirisha-godspeed** [godspeedsystems/gs-plugins#103]
Please add documentation about file_size_limit body_size_limit and base_url in express plugin documentation.

**Comment by shirisha-godspeed** [comment]
rectified need specify the size in numbers(5000000) instead of expression (1024*50*50)

**Comment by shirisha-godspeed** [comment]
closed

**Comment by mastersilv3r** [comment]
I do not see documentation update in the plugin readme. It is not closed yet.

**Comment by mastersilv3r** [comment]
@Mohit-Sharma1 the full and proper configuration of http is at the bottom of this page. Move it to top of this page and close this issue. Replace the small configuration with only port and type express at the top of the page with the detailed config

**Comment by mastersilv3r** [comment]
@Mohit-Sharma1 take help of @sundar-godspeed  to close this.. https://github.com/godspeedsystems/gs-plugins/tree/main/plugins/express-as-http

**Comment by mastersilv3r** [comment]
@Mohit-Sharma1 Check my comments in gs-documentation issue number 99 for reference.
