### ISSUE TITLE
Add Mongoose Datasource Plugin

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#110]
## The Problem 
We need a Mongoose as Datasource plugin

It should export all Mongoose functions with respective arguments.

**Comment by Mohit-Sharma1** [comment]
publish as plugin

**Comment by mastersilv3r** [comment]
@sundar-godspeed Please add this datasource to list of datasource plugins documentation. This is the link https://github.com/godspeedsystems/gs-plugins/tree/main/plugins/mongoose-as-datasource
