### ISSUE TITLE
Add encryption in Prisma plugin

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#128]
Enable AES-256 GCM both way deterministic hashing encryption in Prisma plugin in V2 [just like in V1](https://godspeed.systems/docs/v1/microservices/datasources/datastore#846-prisma-encryption-of-fields)

In your prisma schema, add /// @encrypted to the fields you want to encrypts.
For example, email field in below schema:
```
generator client {
  provider = "prisma-client-js"
  output   = "./generated-clients/mongo"
  previewFeatures = ["metrics"]
}

datasource db {
  provider = "mongodb"
  url      = env("MONGO_TEST_URL")
}

model User1 {
  id        String      @id @default(auto()) @map("_id") @db.ObjectId
  createdAt DateTime @default(now())
  email     String   @unique /// @encrypted
  name      String?
}
```
#### Configuration
You can specify prisma_secret in [environment configuration]
For example, this is the sample configuration, set PRISMA_SECRET as env variable:
in custom-environment-variables.yaml
```
prisma_secret: PRISMA_SECRET # secret used to generate hash of prisma fields
```

**Comment by gurjotmindgrep** [comment]
To use this feature:
Upgrade version to `@godspeedsystems/plugins-prisma-as-datastore: ^1.0.6`
