### ISSUE TITLE
Update Graphql plugin to use Apollo 4

### ISSUE THREAD

**Issue by mastersilv3r** [godspeedsystems/gs-plugins#139]
## The Problem 

We are currently using old version of Apollo Graphql server
## The Solution

- [x] Upgrade to latest 4.0 version and start as standalone server.
- [ ] Update the documentation of the plugin to tell developer about it. 
- [x] It should support jwt auth just like express server configl, from default.yaml
- [x] It should support adding port via default.yaml
- [x] The `godspeed gen-graphql-schema` command should read the specified event source's events and create graphql schema from it. This schema should be saved in `src/datasources` as `<eventsource_name>.graphql`
- [x] Server should start from that graphql schema
- [x] Start Apollo server in standalone mode

## How will we solve

(Provide an overview of how the proposed solution will be implemented.)

**Comment by xCodeMuse** [comment]
WIP fix of graphQL plugin, once done we close this issue.

@sakshiarora386 update here with the issue number.

**Comment by sakshiarora386** [comment]
Issue with GraphQL Eventsource Plugin on Windows #180
