### ISSUE TITLE
Add MongoDB Integration with Mongoose

### ISSUE THREAD

**Issue by shirisha-godspeed** [godspeedsystems/gs-plugins#16]
/bounty $30

**Objective:**
We aim to enhance our project by integrating MongoDB, a powerful NoSQL database, and we'll achieve this using the popular "mongoose" npm package. 
**Requirements:**

1. **Package Dependency:** The developer will need to integrate the [mongoose](https://www.npmjs.com/package/mongoose)  npm package into our project to enable MongoDB integration. Ensure that the package is correctly added and integrated with our existing codebase.

2. **Database Configuration:** Set up the MongoDB connection using "mongoose." This includes configuring connection parameters, handling connection errors, and managing connections efficiently.

3. **Schema Design:** Define MongoDB schema(s) that suit our project's data structure. Ensure that the schema design aligns with our application's needs.

4. **CRUD Operations:** Implement basic CRUD (Create, Read, Update, Delete) operations using "mongoose" to interact with MongoDB collections. Ensure that data is stored and retrieved accurately.

5. **Error Handling:** Implement error handling for MongoDB operations. Ensure that error messages are clear and informative for debugging purposes.

6. **Documentation:** Create comprehensive documentation on how to use the MongoDB integration with "mongoose." This should include installation instructions, configuration guidance, and code examples.

7. **Testing:** Perform thorough testing to validate the reliability and performance of the MongoDB integration. Include unit tests and, if applicable, integration tests.

**Acceptance Criteria:**
- MongoDB should be successfully integrated into our project using "mongoose."
- CRUD operations should work without errors and handle data accurately.
- The MongoDB connection should be well-configured and resilient to errors.
- Clear and comprehensive documentation should be available for users.
- Tests should ensure the reliability and accuracy of the MongoDB integration.

**How to Claim This Bounty:**
1. Fork this repository to your GitHub account.
2. Create a new branch for your work.
3. Implement MongoDB integration using the "mongoose" npm package, following the requirements mentioned above.
4. Submit a pull request to this repository's main branch.
5. Include comprehensive documentation and tests in your pull request.
6. We will review your contribution, and if it meets our criteria, you will receive the specified bounty.

If you have any questions or need further clarification on this issue, please don't hesitate to ask in the comments section. Thank you for contributing to our open-source project!

**Comment by melsonic** [comment]
Hi, @shirisha-godspeed I have read the problem statement and analyzed the repo a bit, as of now to solve this problem I need to create a MongoDB folder inside plugins and write the logic inside datasources. But I do have some questions:-

1. How can I locally run and test the repo if everything is working fine or not after making any changes? I didn't find anything related to setting up the project locally (the package.json file is missing in the main repo).
2. Could you please elaborate the point number 3 a bit also? How can Database schemas be predefined since It will be different for different applications?

**Comment by kushal-mindgrep** [comment]
@infysumanta Thank you for your PR! We'll review and test it. We'll get back to you soon.
