### ISSUE TITLE
Add Redis integration with ioredis

### ISSUE THREAD

**Issue by shirisha-godspeed** [godspeedsystems/gs-plugins#39]
**Objective:**
We aim to introduce a Redis Plugin to our project to enable seamless interaction with Redis databases. Redis is a crucial data store for caching and managing data in various applications.

**Requirements:**

1. **Package Dependency:** The developer will need to integrate the [ioredis](https://www.npmjs.com/package/ioredis) npm package into our project to create the Redis Plugin.

2. **Plugin Functionality:** The Redis Plugin should provide the following core functionalities:
   - [ ] Establish a connection to a Redis server with support for connection pooling and failover mechanisms.
   - [ ] Perform basic Redis operations, such as setting and getting key-value pairs.
   - [ ] Support for more advanced Redis features like Pub/Sub for messaging, transactions, and Lua scripting.
   - [ ] Error handling and reporting for Redis operations.

3. **Configuration:** The plugin should allow users to configure Redis connections and options easily. This includes specifying connection details, pool settings, and other Redis-specific configurations. Document the configuration process for user convenience.

4. **Documentation:** Comprehensive documentation is crucial. The developer should provide clear and concise documentation on how to use the Redis Plugin, including installation instructions, configuration guidelines, usage examples, and best practices for Redis.

5. **Testing:** Thorough testing is essential to ensure the reliability and accuracy of the plugin's Redis operations. Include unit tests and consider providing sample Redis operations for testing.

**Acceptance Criteria:**
- The Redis Plugin should be successfully integrated into our project.
- All specified functionalities mentioned above should work without errors.
- The plugin should interact with Redis databases accurately.
- The code should be well-documented and adhere to our project's coding standards.
- Tests should be in place to ensure the reliability of the Redis operations.

**How to Claim This Bounty:**
1. Fork this repository to your GitHub account.
2. Create a new branch for your work.
3. Implement the Redis Plugin using the "ioredis" npm package, following the requirements mentioned above.
4. Submit a pull request to this repository's main branch.
5. Include comprehensive documentation and tests in your pull request.
6. We will review your contribution, and if it meets our criteria, you will receive the specified bounty.

If you have any questions or need further clarification on this issue, please don't hesitate to ask in the comments section.

---

**Comment by mastersilv3r** [comment]
This plugin has been made
