### ISSUE TITLE
Add RabbitMQ Message Broker Plugin

### ISSUE THREAD

**Issue by kushal-godspeed** [godspeedsystems/gs-plugins#6]
/bounty $50

**Objective:**
We are looking to enhance our project by adding support for RabbitMQ as a message broker.
**Requirements:**

1. **Package Dependency:** The developer will need to add the [amqplib](https://www.npmjs.com/package/amqplib) npm package to create this RabbitMQ plugin. Ensure that the package is added correctly and that it integrates seamlessly with our existing codebase.

2. **Plugin Functionality:** The plugin should provide the following functionalities:
   - [ ] Establish a connection to the RabbitMQ server.
   - [ ] Create and manage queues and exchanges.
   - [ ] Publish messages to RabbitMQ.
   - [ ] Consume messages from RabbitMQ.
   - [ ] Handle connection errors and retries.

3. **Configuration:** The plugin should allow for configuration of RabbitMQ server details, such as hostname, port, credentials, etc. Make sure it's well-documented for easy configuration by users.

4. **Documentation:** Comprehensive documentation is essential. The developer should provide clear and concise documentation on how to use the RabbitMQ plugin, including installation instructions, configuration, and code examples.

5. **Testing:** Thoroughly test the plugin to ensure its reliability and robustness. Include unit tests and possibly integration tests if applicable.

**Acceptance Criteria:**
- The RabbitMQ plugin should be successfully integrated into our project.
- All required functionalities mentioned above should work without errors.
- The code should be well-documented and adhere to our project's coding standards.
- Tests should be in place to ensure the reliability of the plugin.

**How to Claim This Bounty:**
1. Fork this repository to your GitHub account.
2. Create a new branch for your work.
3. Implement the RabbitMQ plugin following the requirements mentioned above.
4. Submit a pull request to this repository's main branch.
5. Include relevant documentation and tests in your pull request.
6. We will review your contribution, and if it meets our criteria, you will receive the specified bounty.

Please feel free to ask questions or seek clarifications in the comments section if you have any doubts about this issue. Thank you for contributing to our open-source project!

**Comment by melsonic** [comment]
Hey @kushal-mindgrep can you please check the linked PR ?
