### ISSUE TITLE
feature: Fastify plugin

### ISSUE THREAD

**Issue by pavan-godspeed** [godspeedsystems/gs-plugins#79]
# Feature Request: [Fastify Plugin](https://github.com/godspeedsystems/gs-plugins/pull/72) Integration

### Motivation
The integration of a Fastify plugin aims to leverage the unique strengths of the Fastify web framework within the Godspeed ecosystem. Fastify, known for its performance and minimal overhead, offers several advantages over traditional frameworks like Express.

### Why Choose Fastify
1. **Performance:** Fastify is designed to be highly performant, outpacing many other Node.js frameworks, including Express. Its minimalistic architecture and focus on speed make it an excellent choice for applications with high-performance requirements.

2. **Low Overhead:** Fastify comes with a low overhead, resulting in faster response times and reduced memory consumption. This makes it particularly suitable for resource-intensive applications and microservices architectures.

3. **Schema-Based Validation:** Fastify includes built-in support for JSON Schema-based validation. This feature enhances the reliability of APIs by validating request and response payloads, ensuring data consistency and reducing the likelihood of runtime errors.

4. **Plugin System:** Fastify's modular and extensible architecture is built around a powerful plugin system. This allows developers to easily add, remove, or replace functionalities, promoting code organization and maintainability.

5. **Asynchronous Request Hooks:** Fastify provides a unique approach to request hooks by allowing asynchronous handlers. This can be beneficial for tasks such as asynchronous validation or data fetching during the request lifecycle.

6. **Typed Routes:** Fastify supports TypeScript out of the box and encourages the use of TypeScript for defining routes. This leads to improved code quality, better developer experience, and reduced chances of runtime errors.

### Feature Proposal
The integration of the Fastify plugin into the Godspeed framework will harness these advantages, providing users with a robust and performant solution for handling HTTP events. The proposed integration aligns with Godspeed's commitment to supporting cutting-edge technologies and providing developers with the tools they need to build scalable and efficient applications.

### Testing
- This plugin is tested on HTTP methods (GET, POST, PUT, DELETE) and swagger UI is also integrated in it.
- Authorization is also tested on fastify events.

### Expected Behavior
The integration of the Fastify plugin should seamlessly bring Fastify's benefits to Godspeed, offering developers a high-performance, low-overhead, and schema-driven solution for handling HTTP events.

**Comment by mastersilv3r** [comment]
@sundar-godspeed need to close this asap
Please test that all these features should run just like express

- [ ] base url
- [ ] port
- [ ] request body size limit
- [ ] file size limit and ability to upload a file
- [ ] jwt enabledment

**Comment by sundar-godspeed** [comment]
file upload feature not yet implemented!
Working on that!
